name: diamondgroup
favicon: null
layout_spectrum: 0.18206551088951528
typography_spectrum: 0.8500546289142221
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0487645142711699
  lightness: 0.07922368450090289
  saturation: 0.6670486384537071
  rhythmicContrast: 0.8067992283031344
purpose: []
